### ISSUE TITLE
TypeError: Function.prototype.toString requires that 'this' be a Function

### ISSUE THREAD

**Issue by mk-pmb** [joyent/node-assert-plus#34]
```
/…/node_modules/verror/node_modules/assert-plus/assert.js:1
TypeError: Function.prototype.toString requires that 'this' be a Function
    at Proxy.toString (<anonymous>)
    at Object.<anonymous> (/…/node_modules/verror/node_modules/assert-plus/assert.js:5:31)
```

require('verror/package.json').version = 1.10.0
require('verror/node_modules/assert-plus/package.json').version = 1.0.0
Node.js v8.15.0, npm v6.4.1, Ubuntu 14.04.5 LTS trusty

**Comment by melloc** [comment]
@mk-pmb Can you provide a minimal example that reproduces this? I'm not sure how this would happen.

**Comment by mk-pmb** [comment]
I wondered as well, because the lines in the source didn't really match. Meanwhile I tracked it down and it seems to be an error caused from another module that modifies the module system.
